// Brand Registry - Auto-generated by school-manager.js
// DO NOT EDIT MANUALLY - Run "npm run school:add" to add new schools

import aaimathajiConfig from './aaimathaji/brand.config.json';
import bsschoolConfig from './bsschool/brand.config.json';
import crescentConfig from './crescent/brand.config.json';
import littleflowerConfig from './littleflower/brand.config.json';
import psseniorConfig from './pssenior/brand.config.json';
import railwaybalabhavanConfig from './railwaybalabhavan/brand.config.json';
import sivakasiConfig from './sivakasi/brand.config.json';
import stdominicsConfig from './stdominics/brand.config.json';

// Export all brand configs as a registry
export const brandRegistry: Record<string, any> = {
  aaimathaji: aaimathajiConfig,
  bsschool: bsschoolConfig,
  crescent: crescentConfig,
  littleflower: littleflowerConfig,
  pssenior: psseniorConfig,
  railwaybalabhavan: railwaybalabhavanConfig,
  sivakasi: sivakasiConfig,
  stdominics: stdominicsConfig,
};

// Export individual configs if needed
export { aaimathajiConfig, bsschoolConfig, crescentConfig, littleflowerConfig, psseniorConfig, railwaybalabhavanConfig, sivakasiConfig, stdominicsConfig };
