// Brand Registry - Auto-generated by school-manager.js
// DO NOT EDIT MANUALLY - Run "npm run school:add" to add new schools

import aadhithyaConfig from './aadhithya/brand.config.json';
import aaimathajiConfig from './aaimathaji/brand.config.json';
import alphacbseConfig from './alphacbse/brand.config.json';
import alphamatConfig from './alphamat/brand.config.json';
import alphatechnoConfig from './alphatechno/brand.config.json';
import avlConfig from './avl/brand.config.json';
import balakrishnaConfig from './balakrishna/brand.config.json';
import bsschoolConfig from './bsschool/brand.config.json';
import carmelnpConfig from './carmelnp/brand.config.json';
import crescentConfig from './crescent/brand.config.json';
import csistthomasConfig from './csistthomas/brand.config.json';
import doonConfig from './doon/brand.config.json';
import gloryConfig from './glory/brand.config.json';
import greenworldschoolConfig from './greenworldschool/brand.config.json';
import holyangelsConfig from './holyangels/brand.config.json';
import holycresentmatricConfig from './holycresentmatric/brand.config.json';
import holycresentnazConfig from './holycresentnaz/brand.config.json';
import holycresentsriConfig from './holycresentsri/brand.config.json';
import holycresentthiruConfig from './holycresentthiru/brand.config.json';
import infantConfig from './infant/brand.config.json';
import islamiahConfig from './islamiah/brand.config.json';
import joshuaConfig from './joshua/brand.config.json';
import kalaimagalConfig from './kalaimagal/brand.config.json';
import kamalanehruConfig from './kamalanehru/brand.config.json';
import littleflowerConfig from './littleflower/brand.config.json';
import measiConfig from './measi/brand.config.json';
import mountcarmelConfig from './mountcarmel/brand.config.json';
import mountsenoConfig from './mountseno/brand.config.json';
import nationallotusConfig from './nationallotus/brand.config.json';
import ourladyexcelConfig from './ourladyexcel/brand.config.json';
import ourladynpConfig from './ourladynp/brand.config.json';
import periyarConfig from './periyar/brand.config.json';
import psseniorConfig from './pssenior/brand.config.json';
import railwaybalabhavanConfig from './railwaybalabhavan/brand.config.json';
import rpccbseConfig from './rpccbse/brand.config.json';
import rukmaniConfig from './rukmani/brand.config.json';
import sivakasiConfig from './sivakasi/brand.config.json';
import stdominicsConfig from './stdominics/brand.config.json';
import stjosephkoduConfig from './stjosephkodu/brand.config.json';
import stmosesConfig from './stmoses/brand.config.json';
import templegreenConfig from './templegreen/brand.config.json';
import templeparkConfig from './templepark/brand.config.json';
import udhayamglobalConfig from './udhayamglobal/brand.config.json';
import venkateshwaraConfig from './venkateshwara/brand.config.json';
import vidyaratnaConfig from './vidyaratna/brand.config.json';
import vipschoolConfig from './vipschool/brand.config.json';
import vnrvivekanandaConfig from './vnrvivekananda/brand.config.json';
import vsnmatricConfig from './vsnmatric/brand.config.json';

// Export all brand configs as a registry
export const brandRegistry: Record<string, any> = {
  aadhithya: aadhithyaConfig,
  aaimathaji: aaimathajiConfig,
  alphacbse: alphacbseConfig,
  alphamat: alphamatConfig,
  alphatechno: alphatechnoConfig,
  avl: avlConfig,
  balakrishna: balakrishnaConfig,
  bsschool: bsschoolConfig,
  carmelnp: carmelnpConfig,
  crescent: crescentConfig,
  csistthomas: csistthomasConfig,
  doon: doonConfig,
  glory: gloryConfig,
  greenworldschool: greenworldschoolConfig,
  holyangels: holyangelsConfig,
  holycresentmatric: holycresentmatricConfig,
  holycresentnaz: holycresentnazConfig,
  holycresentsri: holycresentsriConfig,
  holycresentthiru: holycresentthiruConfig,
  infant: infantConfig,
  islamiah: islamiahConfig,
  joshua: joshuaConfig,
  kalaimagal: kalaimagalConfig,
  kamalanehru: kamalanehruConfig,
  littleflower: littleflowerConfig,
  measi: measiConfig,
  mountcarmel: mountcarmelConfig,
  mountseno: mountsenoConfig,
  nationallotus: nationallotusConfig,
  ourladyexcel: ourladyexcelConfig,
  ourladynp: ourladynpConfig,
  periyar: periyarConfig,
  pssenior: psseniorConfig,
  railwaybalabhavan: railwaybalabhavanConfig,
  rpccbse: rpccbseConfig,
  rukmani: rukmaniConfig,
  sivakasi: sivakasiConfig,
  stdominics: stdominicsConfig,
  stjosephkodu: stjosephkoduConfig,
  stmoses: stmosesConfig,
  templegreen: templegreenConfig,
  templepark: templeparkConfig,
  udhayamglobal: udhayamglobalConfig,
  venkateshwara: venkateshwaraConfig,
  vidyaratna: vidyaratnaConfig,
  vipschool: vipschoolConfig,
  vnrvivekananda: vnrvivekanandaConfig,
  vsnmatric: vsnmatricConfig,
};

// Export individual configs if needed
export { aadhithyaConfig, aaimathajiConfig, alphacbseConfig, alphamatConfig, alphatechnoConfig, avlConfig, balakrishnaConfig, bsschoolConfig, carmelnpConfig, crescentConfig, csistthomasConfig, doonConfig, gloryConfig, greenworldschoolConfig, holyangelsConfig, holycresentmatricConfig, holycresentnazConfig, holycresentsriConfig, holycresentthiruConfig, infantConfig, islamiahConfig, joshuaConfig, kalaimagalConfig, kamalanehruConfig, littleflowerConfig, measiConfig, mountcarmelConfig, mountsenoConfig, nationallotusConfig, ourladyexcelConfig, ourladynpConfig, periyarConfig, psseniorConfig, railwaybalabhavanConfig, rpccbseConfig, rukmaniConfig, sivakasiConfig, stdominicsConfig, stjosephkoduConfig, stmosesConfig, templegreenConfig, templeparkConfig, udhayamglobalConfig, venkateshwaraConfig, vidyaratnaConfig, vipschoolConfig, vnrvivekanandaConfig, vsnmatricConfig };
